import type { LocationData, CurrentWeather, ForecastDay, HourlyForecast, WeatherRisk } from '../types/index.js';

export const mockLocations: LocationData[] = [
  { id: 'new-delhi', name: 'New Delhi', region: 'Delhi', country: 'India', lat: 28.6139, lon: 77.209 },
  { id: 'mumbai', name: 'Mumbai', region: 'Maharashtra', country: 'India', lat: 19.076, lon: 72.8777 },
  { id: 'bengaluru', name: 'Bengaluru', region: 'Karnataka', country: 'India', lat: 12.9716, lon: 77.5946 },
  { id: 'chennai', name: 'Chennai', region: 'Tamil Nadu', country: 'India', lat: 13.0827, lon: 80.2707 },
  { id: 'kolkata', name: 'Kolkata', region: 'West Bengal', country: 'India', lat: 22.5726, lon: 88.3639 },
  { id: 'jaipur', name: 'Jaipur', region: 'Rajasthan', country: 'India', lat: 26.9124, lon: 75.7873 },
];

export const mockWeatherData: Record<string, CurrentWeather> = {
  'new-delhi': {
    location: 'New Delhi',
    region: 'Delhi',
    country: 'India',
    temperature: 34,
    feelsLike: 38,
    condition: { main: 'Partly Cloudy', description: 'Partly cloudy with haze', icon: 'cloud-sun' },
    humidity: 62,
    windSpeed: 14,
    windDirection: 'SW',
    visibility: 6,
    pressure: 1006,
    uvIndex: 8,
    lastUpdated: new Date().toISOString(),
  },
  'mumbai': {
    location: 'Mumbai',
    region: 'Maharashtra',
    country: 'India',
    temperature: 29,
    feelsLike: 34,
    condition: { main: 'Heavy Rain', description: 'Heavy rainfall expected', icon: 'cloud-rain' },
    humidity: 88,
    windSpeed: 22,
    windDirection: 'W',
    visibility: 3,
    pressure: 1004,
    uvIndex: 3,
    lastUpdated: new Date().toISOString(),
  },
  'bengaluru': {
    location: 'Bengaluru',
    region: 'Karnataka',
    country: 'India',
    temperature: 24,
    feelsLike: 25,
    condition: { main: 'Cloudy', description: 'Overcast skies', icon: 'cloud' },
    humidity: 72,
    windSpeed: 10,
    windDirection: 'E',
    visibility: 8,
    pressure: 1012,
    uvIndex: 4,
    lastUpdated: new Date().toISOString(),
  },
  'chennai': {
    location: 'Chennai',
    region: 'Tamil Nadu',
    country: 'India',
    temperature: 33,
    feelsLike: 39,
    condition: { main: 'Sunny', description: 'Clear and sunny', icon: 'sun' },
    humidity: 70,
    windSpeed: 16,
    windDirection: 'SE',
    visibility: 10,
    pressure: 1008,
    uvIndex: 9,
    lastUpdated: new Date().toISOString(),
  },
  'kolkata': {
    location: 'Kolkata',
    region: 'West Bengal',
    country: 'India',
    temperature: 31,
    feelsLike: 36,
    condition: { main: 'Thunderstorm', description: 'Thunderstorm expected', icon: 'cloud-lightning' },
    humidity: 80,
    windSpeed: 20,
    windDirection: 'S',
    visibility: 5,
    pressure: 1003,
    uvIndex: 5,
    lastUpdated: new Date().toISOString(),
  },
  'jaipur': {
    location: 'Jaipur',
    region: 'Rajasthan',
    country: 'India',
    temperature: 38,
    feelsLike: 42,
    condition: { main: 'Hot', description: 'Extreme heat', icon: 'sun' },
    humidity: 35,
    windSpeed: 12,
    windDirection: 'NW',
    visibility: 12,
    pressure: 1005,
    uvIndex: 11,
    lastUpdated: new Date().toISOString(),
  },
};

export const mockForecastData: Record<string, ForecastDay[]> = {
  'new-delhi': [
    { date: '2026-08-27', day: 'Today', high: 35, low: 27, condition: { main: 'Partly Cloudy', description: 'Partly cloudy', icon: 'cloud-sun' }, rainProbability: 20, humidity: 62, windSpeed: 14 },
    { date: '2026-08-28', day: 'Thu', high: 34, low: 26, condition: { main: 'Rain', description: 'Light rain', icon: 'cloud-rain' }, rainProbability: 65, humidity: 70, windSpeed: 16 },
    { date: '2026-08-29', day: 'Fri', high: 32, low: 25, condition: { main: 'Rain', description: 'Moderate rain', icon: 'cloud-rain' }, rainProbability: 80, humidity: 78, windSpeed: 18 },
    { date: '2026-08-30', day: 'Sat', high: 33, low: 26, condition: { main: 'Cloudy', description: 'Overcast', icon: 'cloud' }, rainProbability: 40, humidity: 68, windSpeed: 12 },
    { date: '2026-08-31', day: 'Sun', high: 35, low: 27, condition: { main: 'Partly Cloudy', description: 'Partly cloudy', icon: 'cloud-sun' }, rainProbability: 15, humidity: 58, windSpeed: 10 },
    { date: '2026-09-01', day: 'Mon', high: 36, low: 28, condition: { main: 'Sunny', description: 'Clear sky', icon: 'sun' }, rainProbability: 5, humidity: 50, windSpeed: 8 },
    { date: '2026-09-02', day: 'Tue', high: 34, low: 27, condition: { main: 'Partly Cloudy', description: 'Partly cloudy', icon: 'cloud-sun' }, rainProbability: 25, humidity: 60, windSpeed: 14 },
  ],
  'mumbai': [
    { date: '2026-08-27', day: 'Today', high: 30, low: 25, condition: { main: 'Heavy Rain', description: 'Heavy rain', icon: 'cloud-rain' }, rainProbability: 90, humidity: 88, windSpeed: 22 },
    { date: '2026-08-28', day: 'Thu', high: 29, low: 25, condition: { main: 'Rain', description: 'Moderate rain', icon: 'cloud-rain' }, rainProbability: 85, humidity: 86, windSpeed: 20 },
    { date: '2026-08-29', day: 'Fri', high: 29, low: 24, condition: { main: 'Rain', description: 'Light rain', icon: 'cloud-rain' }, rainProbability: 70, humidity: 82, windSpeed: 18 },
    { date: '2026-08-30', day: 'Sat', high: 30, low: 25, condition: { main: 'Cloudy', description: 'Overcast', icon: 'cloud' }, rainProbability: 50, humidity: 78, windSpeed: 14 },
    { date: '2026-08-31', day: 'Sun', high: 31, low: 26, condition: { main: 'Partly Cloudy', description: 'Partly cloudy', icon: 'cloud-sun' }, rainProbability: 35, humidity: 72, windSpeed: 12 },
    { date: '2026-09-01', day: 'Mon', high: 30, low: 25, condition: { main: 'Rain', description: 'Showers', icon: 'cloud-rain' }, rainProbability: 60, humidity: 80, windSpeed: 16 },
    { date: '2026-09-02', day: 'Tue', high: 29, low: 25, condition: { main: 'Heavy Rain', description: 'Heavy rain', icon: 'cloud-rain' }, rainProbability: 88, humidity: 90, windSpeed: 24 },
  ],
  'bengaluru': [
    { date: '2026-08-27', day: 'Today', high: 26, low: 19, condition: { main: 'Cloudy', description: 'Overcast', icon: 'cloud' }, rainProbability: 45, humidity: 72, windSpeed: 10 },
    { date: '2026-08-28', day: 'Thu', high: 27, low: 20, condition: { main: 'Rain', description: 'Light showers', icon: 'cloud-rain' }, rainProbability: 55, humidity: 75, windSpeed: 12 },
    { date: '2026-08-29', day: 'Fri', high: 25, low: 19, condition: { main: 'Rain', description: 'Moderate rain', icon: 'cloud-rain' }, rainProbability: 70, humidity: 80, windSpeed: 14 },
    { date: '2026-08-30', day: 'Sat', high: 26, low: 20, condition: { main: 'Partly Cloudy', description: 'Partly cloudy', icon: 'cloud-sun' }, rainProbability: 30, humidity: 68, windSpeed: 8 },
    { date: '2026-08-31', day: 'Sun', high: 27, low: 20, condition: { main: 'Sunny', description: 'Clear', icon: 'sun' }, rainProbability: 10, humidity: 60, windSpeed: 6 },
    { date: '2026-09-01', day: 'Mon', high: 26, low: 19, condition: { main: 'Cloudy', description: 'Overcast', icon: 'cloud' }, rainProbability: 40, humidity: 70, windSpeed: 10 },
    { date: '2026-09-02', day: 'Tue', high: 25, low: 19, condition: { main: 'Rain', description: 'Light rain', icon: 'cloud-rain' }, rainProbability: 60, humidity: 76, windSpeed: 12 },
  ],
  'chennai': [
    { date: '2026-08-27', day: 'Today', high: 34, low: 27, condition: { main: 'Sunny', description: 'Clear', icon: 'sun' }, rainProbability: 5, humidity: 70, windSpeed: 16 },
    { date: '2026-08-28', day: 'Thu', high: 35, low: 28, condition: { main: 'Sunny', description: 'Clear', icon: 'sun' }, rainProbability: 5, humidity: 68, windSpeed: 14 },
    { date: '2026-08-29', day: 'Fri', high: 34, low: 27, condition: { main: 'Partly Cloudy', description: 'Hazy', icon: 'cloud-sun' }, rainProbability: 15, humidity: 72, windSpeed: 12 },
    { date: '2026-08-30', day: 'Sat', high: 33, low: 27, condition: { main: 'Cloudy', description: 'Overcast', icon: 'cloud' }, rainProbability: 30, humidity: 75, windSpeed: 14 },
    { date: '2026-08-31', day: 'Sun', high: 34, low: 28, condition: { main: 'Sunny', description: 'Clear', icon: 'sun' }, rainProbability: 10, humidity: 65, windSpeed: 16 },
    { date: '2026-09-01', day: 'Mon', high: 35, low: 28, condition: { main: 'Sunny', description: 'Hot and clear', icon: 'sun' }, rainProbability: 5, humidity: 62, windSpeed: 18 },
    { date: '2026-09-02', day: 'Tue', high: 34, low: 27, condition: { main: 'Partly Cloudy', description: 'Partly cloudy', icon: 'cloud-sun' }, rainProbability: 20, humidity: 70, windSpeed: 14 },
  ],
  'kolkata': [
    { date: '2026-08-27', day: 'Today', high: 32, low: 26, condition: { main: 'Thunderstorm', description: 'Thunderstorm', icon: 'cloud-lightning' }, rainProbability: 75, humidity: 80, windSpeed: 20 },
    { date: '2026-08-28', day: 'Thu', high: 31, low: 26, condition: { main: 'Rain', description: 'Heavy rain', icon: 'cloud-rain' }, rainProbability: 80, humidity: 84, windSpeed: 22 },
    { date: '2026-08-29', day: 'Fri', high: 30, low: 25, condition: { main: 'Rain', description: 'Moderate rain', icon: 'cloud-rain' }, rainProbability: 65, humidity: 80, windSpeed: 16 },
    { date: '2026-08-30', day: 'Sat', high: 31, low: 26, condition: { main: 'Cloudy', description: 'Overcast', icon: 'cloud' }, rainProbability: 40, humidity: 74, windSpeed: 12 },
    { date: '2026-08-31', day: 'Sun', high: 32, low: 26, condition: { main: 'Partly Cloudy', description: 'Partly cloudy', icon: 'cloud-sun' }, rainProbability: 25, humidity: 68, windSpeed: 10 },
    { date: '2026-09-01', day: 'Mon', high: 33, low: 27, condition: { main: 'Sunny', description: 'Clear', icon: 'sun' }, rainProbability: 10, humidity: 60, windSpeed: 8 },
    { date: '2026-09-02', day: 'Tue', high: 32, low: 26, condition: { main: 'Partly Cloudy', description: 'Partly cloudy', icon: 'cloud-sun' }, rainProbability: 30, humidity: 66, windSpeed: 14 },
  ],
  'jaipur': [
    { date: '2026-08-27', day: 'Today', high: 40, low: 29, condition: { main: 'Hot', description: 'Extreme heat', icon: 'sun' }, rainProbability: 5, humidity: 35, windSpeed: 12 },
    { date: '2026-08-28', day: 'Thu', high: 39, low: 28, condition: { main: 'Sunny', description: 'Clear', icon: 'sun' }, rainProbability: 5, humidity: 38, windSpeed: 10 },
    { date: '2026-08-29', day: 'Fri', high: 38, low: 28, condition: { main: 'Partly Cloudy', description: 'Partly cloudy', icon: 'cloud-sun' }, rainProbability: 20, humidity: 42, windSpeed: 14 },
    { date: '2026-08-30', day: 'Sat', high: 37, low: 27, condition: { main: 'Cloudy', description: 'Overcast', icon: 'cloud' }, rainProbability: 35, humidity: 50, windSpeed: 16 },
    { date: '2026-08-31', day: 'Sun', high: 36, low: 27, condition: { main: 'Rain', description: 'Light showers', icon: 'cloud-rain' }, rainProbability: 55, humidity: 58, windSpeed: 14 },
    { date: '2026-09-01', day: 'Mon', high: 38, low: 28, condition: { main: 'Sunny', description: 'Clear', icon: 'sun' }, rainProbability: 10, humidity: 40, windSpeed: 10 },
    { date: '2026-09-02', day: 'Tue', high: 39, low: 29, condition: { main: 'Hot', description: 'Very hot', icon: 'sun' }, rainProbability: 5, humidity: 34, windSpeed: 12 },
  ],
};

export const mockHourlyForecast: HourlyForecast[] = [
  { time: '9 AM', temperature: 30, condition: { main: 'Partly Cloudy', description: '', icon: 'cloud-sun' }, rainProbability: 10 },
  { time: '12 PM', temperature: 34, condition: { main: 'Sunny', description: '', icon: 'sun' }, rainProbability: 5 },
  { time: '3 PM', temperature: 35, condition: { main: 'Partly Cloudy', description: '', icon: 'cloud-sun' }, rainProbability: 20 },
  { time: '6 PM', temperature: 32, condition: { main: 'Cloudy', description: '', icon: 'cloud' }, rainProbability: 40 },
  { time: '9 PM', temperature: 29, condition: { main: 'Rain', description: '', icon: 'cloud-rain' }, rainProbability: 60 },
  { time: '12 AM', temperature: 27, condition: { main: 'Cloudy', description: '', icon: 'cloud' }, rainProbability: 30 },
];

export const mockRisksData: Record<string, WeatherRisk[]> = {
  'new-delhi': [
    { id: 'r1', type: 'heat', level: 'high', title: 'Heat Advisory', description: 'Temperature expected to exceed 40°C. Stay hydrated and avoid prolonged outdoor exposure.', icon: 'thermometer', timePeriod: 'Today, 12 PM – 5 PM', isActive: true },
    { id: 'r2', type: 'rain', level: 'moderate', title: 'Rain Alert', description: 'Rain probability is increasing during the evening. Carry an umbrella.', icon: 'cloud-rain', timePeriod: 'Today, 6 PM – 11 PM', isActive: true },
    { id: 'r3', type: 'air-quality', level: 'moderate', title: 'Air Quality Warning', description: 'AQI levels are moderate. Sensitive groups should limit outdoor activity.', icon: 'wind', timePeriod: 'Next 24 hours', isActive: true },
    { id: 'r4', type: 'storm', level: 'low', title: 'Storm Watch', description: 'Low probability of isolated thunderstorms in the region.', icon: 'cloud-lightning', timePeriod: 'Tomorrow, 3 PM – 9 PM', isActive: false },
  ],
  'mumbai': [
    { id: 'r1', type: 'rain', level: 'severe', title: 'Heavy Rain Warning', description: 'Very heavy rainfall expected. Risk of waterlogging in low-lying areas.', icon: 'cloud-rain', timePeriod: 'Next 48 hours', isActive: true },
    { id: 'r2', type: 'flood', level: 'high', title: 'Flood Risk', description: 'High risk of urban flooding in low-lying areas due to continuous rainfall.', icon: 'waves', timePeriod: 'Today – Tomorrow', isActive: true },
    { id: 'r3', type: 'wind', level: 'moderate', title: 'Strong Wind Alert', description: 'Wind gusts up to 50 km/h expected along the coast.', icon: 'wind', timePeriod: 'Today evening', isActive: true },
  ],
  'bengaluru': [
    { id: 'r1', type: 'rain', level: 'moderate', title: 'Rain Alert', description: 'Moderate rainfall expected in the afternoon and evening.', icon: 'cloud-rain', timePeriod: 'Today, 2 PM – 8 PM', isActive: true },
    { id: 'r2', type: 'traffic', level: 'low', title: 'Traffic Advisory', description: 'Rain may cause traffic delays in key areas.', icon: 'alert-triangle', timePeriod: 'Today evening', isActive: false },
  ],
  'chennai': [
    { id: 'r1', type: 'heat', level: 'high', title: 'Heat Warning', description: 'Extreme heat expected. UV index very high. Avoid direct sun exposure.', icon: 'thermometer', timePeriod: 'Today, 11 AM – 4 PM', isActive: true },
    { id: 'r2', type: 'humidity', level: 'moderate', title: 'High Humidity', description: 'Humidity levels above 80%. Heat discomfort likely.', icon: 'droplets', timePeriod: 'All day', isActive: true },
  ],
  'kolkata': [
    { id: 'r1', type: 'storm', level: 'high', title: 'Thunderstorm Warning', description: 'Severe thunderstorms with lightning expected. Stay indoors.', icon: 'cloud-lightning', timePeriod: 'Today, 4 PM – 10 PM', isActive: true },
    { id: 'r2', type: 'rain', level: 'high', title: 'Heavy Rain Alert', description: 'Heavy rainfall may cause waterlogging in several areas.', icon: 'cloud-rain', timePeriod: 'Next 24 hours', isActive: true },
    { id: 'r3', type: 'wind', level: 'moderate', title: 'Wind Advisory', description: 'Strong winds up to 45 km/h during thunderstorms.', icon: 'wind', timePeriod: 'Today evening', isActive: true },
  ],
  'jaipur': [
    { id: 'r1', type: 'heat', level: 'severe', title: 'Extreme Heat Alert', description: 'Temperature may exceed 42°C. Heatstroke risk is very high.', icon: 'thermometer', timePeriod: 'Today – Tomorrow', isActive: true },
    { id: 'r2', type: 'uv', level: 'high', title: 'UV Radiation Alert', description: 'UV index extremely high. Use sun protection.', icon: 'sun', timePeriod: 'Today, 10 AM – 4 PM', isActive: true },
  ],
};
